#!/usr/bin/env python3
"""Generate the built-in catalog's revision pins from catalog.json.

Why this exists
---------------
`ModelCatalog.load()` fetches `catalog.json` over the network and falls back to the
compiled-in `ModelCatalog.builtin` when that fetch fails:

    (try? await fetch(from: url)) ?? .builtin

The built-in list is a hand-written Swift literal, and it carried no revision pins — while
`CatalogEntry.modelID(path:)` resolves `revision ?? "main"`. So any network failure silently
downgraded a shipped app from "the exact bytes that were gated" to "whatever is on main
today", which is the opposite of what the catalog promises.

Rather than generate the whole literal (it carries per-model engineering comments worth
keeping), this generates only the id -> revision map, which `ModelCatalog.builtin` overlays
onto the literal. catalog.json stays the single source of truth for pins; the literal stays
the single source of truth for everything else.

    python3 scripts/gen-builtin-pins.py            # regenerate
    python3 scripts/gen-builtin-pins.py --check    # CI: fail if stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog.json"
OUT = ROOT / "Sources" / "CoreAIKitCore" / "BuiltinPins.swift"

HEADER = """\
// Generated by scripts/gen-builtin-pins.py from catalog.json — do not edit by hand.
//
// The compiled-in fallback catalog is a hand-written literal (ModelCatalog.builtin) so it can
// carry per-model notes. Its revision pins come from here instead, so that a fallback — which
// happens exactly when the network is unavailable — still resolves the reviewed bytes rather
// than whatever the model repo's main branch holds at that moment.

enum BuiltinPins {
    /// Catalog id -> Hugging Face commit hash, mirrored from catalog.json.
    static let byID: [String: String] = [
"""

FOOTER = """\
    ]
}
"""


def render() -> str:
    models = json.loads(CATALOG.read_text())["models"]
    rows = []
    for e in sorted(models, key=lambda m: m["id"]):
        rev = e.get("revision")
        if not rev:
            sys.exit(
                f"catalog.json entry {e['id']!r} has no revision.\n"
                "  Every published entry must be pinned; run scripts/pin-catalog.py --check."
            )
        rows.append(f'        "{e["id"]}": "{rev}",')
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated file is missing or stale")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != want:
            sys.exit(
                f"{OUT.relative_to(ROOT)} is stale.\n"
                "  catalog.json changed without regenerating the built-in pins — a fallback\n"
                "  would resolve an unpinned revision. Fix with:\n"
                "    python3 scripts/gen-builtin-pins.py"
            )
        n = want.count('": "')
        print(f"OK: built-in pins match catalog.json ({n} entries)")
        return

    OUT.write_text(want)
    print(f"wrote {OUT.relative_to(ROOT)} ({want.count('\": \"')} entries)")


if __name__ == "__main__":
    main()
