#!/usr/bin/env python3
"""Measure what each catalog entry downloads, and hold `sizeMB` to it.

    python3 scripts/measure-catalog-sizes.py            # the table
    python3 scripts/measure-catalog-sizes.py --check    # CI: fail if a size is off by more than 2%
    python3 scripts/measure-catalog-sizes.py --write    # set every sizeMB to what was measured

`sizeMB` is the number an adopter is shown before committing to a download, and the number
`capability()` answers with. **It is decimal megabytes — bytes / 1,000,000, rounded — of
everything a first run downloads.** Every reader in the package assumes that unit:
`capability()` and the residency estimate multiply by 1,000,000, `systemone models` and VLChat
divide by 1,000 for GB, and the docs quote decimal GB.

It was typed by hand, and it drifted twice. The nine errors found on 2026-08-05 were iOS
figures estimated as the macOS one doubled. On 2026-09-24, 34 of the 111 variant sizes were
bytes / 1,048,576 (MiB): 4.9% low, enough for `systemone models` to show a 5.77 GB download as
5.5 GB. Another 21 were more than 2% off for other reasons: round-number estimates, a loader's
subtrees left out, iOS figures above what the iOS subtree holds. This script and CI's `--check`
own the number now.

What "a first run downloads" means: `ModelStore` fetches every file under a path, READMEs
included. A loader downloads the variant's path plus the subtrees it pairs with it: a vision
tower, the PLE tables beside a Gemma 4 decoder, TTS glue and a tokenizer, an audio encoder.
The two tables below are those subtrees, read off the loaders. A new multi-bundle entry needs
its loader's subtrees added to them; until then only its variant path is measured. A path named
here that is missing at the pinned revision fails every mode, so a renamed subtree cannot shrink
a number silently.

Summing the whole repo is not a substitute for the tables: several repos publish quantisations
side by side that no loader fetches. qwen3.5-0.8B's holds 10.9 GB at its pin for a 1.3 GB
download.

`--write` rewrites both copies of each number, catalog.json and the built-in literal in
Sources/CoreAIKitCore/ModelCatalog.swift, which `testBuiltinMatchesShippedCatalogFile` holds
equal. The zoo's model cards quote these numbers too; they are generated by the zoo's
`scripts/gen-cards`, and nothing re-runs it for you (on 2026-08-25 five cards were found
advertising a download size the catalog no longer agreed with, one of them by almost 2x).

Reads file metadata from the Hub's API only — no weights are downloaded, and no dependency
beyond the standard library. A repo the Hub cannot answer for is reported and skipped, as
`pin-catalog.py --check` does, so an outage does not fail CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog.json"
SWIFT = ROOT / "Sources" / "CoreAIKitCore" / "ModelCatalog.swift"
TOLERANCE = 0.02

# Subtrees a loader downloads beside the variant path. A list applies to every variant; a
# dict is per variant key, for the loaders that pick a different tower on iOS.
ALSO: dict[str, list[str] | dict[str, list[str]]] = {
    # GemmaModelID (Gemma/KitGemmaModel.swift): decoder + PLE tables.
    "gemma-4-e2b": ["ios-frontend/gemma4_qat_gather_raw"],
    "gemma-4-e4b": ["ios-frontend/gemma4_e4b_qat_gather_raw"],
    # VLModelID (Vision/KitVisionModel.swift): decoder + vision tower.
    "qwen3-vl-2b": ["gpu-pipelined/qwen3_vl_2b_instruct_vision"],
    "qwen3-vl-4b": ["gpu-pipelined/qwen3_vl_4b_instruct_vision"],
    "qwen3-vl-8b": ["gpu-pipelined/qwen3_vl_8b_instruct_vision"],
    "holo2-4b": ["gpu-pipelined/holo2_4b_vision"],
    "minicpm-v-4.6": ["gpu-pipelined/minicpmv46_vision"],
    "lfm2.5-vl-450m": {"macos": ["gpu-pipelined/lfm2_5_vl_450m_vision_fp16"],
                       "ios": ["ios-h18p/lfm2_5_vl_450m_vision_fp16"]},
    "lfm2.5-vl-3b": {"macos": ["gpu-pipelined/lfm2_5_vl_3b_vision_fp16"],
                     "ios": ["ios-h18p/lfm2_5_vl_3b_vision_fp16"]},
    "north-micro-vision": {"macos": ["gpu-pipelined/north_micro_vision_instruct_vision_fp16"],
                           "ios": ["ios-h18p/north_micro_vision_instruct_vision_fp16"]},
    # KitSpeaker (Audio/KitSpeaker.swift): platform bundles + tokenizer + host glue.
    "voxcpm-0.5b": ["tokenizer", "voxcpm_host_glue"],
    "voxcpm2-2b": ["tokenizer", "voxcpm2_host_glue"],
    # KitDialogue (VibeVoice/KitDialogue.swift): graphs + glue, voice caches, embedding table.
    "vibevoice-realtime-0.5b": ["coreai_host/glue", "coreai_host/voices", "coreai_host/embed"],
    # ASRModelID (ASR/KitASRModel.swift): decoder + AuT encoder.
    "qwen3-asr-1.7b": ["gpu-pipelined/qwen3_asr_1.7b_audio_encoder_fp16_k30"],
    # VisualDocumentRetriever (CoreAIKitEmbeddings): doc encoder + query encoder.
    "colmodernvbert": ["query"],
}

# Loaders that never download the variant path itself — it names a flat repo's root or a
# parent directory, for platform gating — and fetch these subtrees instead.
INSTEAD: dict[str, list[str]] = {
    # KitSpeaker: three graphs + host glue at the repo root.
    "kokoro-82m": ["kokoro_predictor.aimodel", "kokoro_prosody.aimodel",
                   "kokoro_vocoder.aimodel", "kokoro_host_glue"],
    # KitDocReader (OCR/KitDocReader.swift).
    "unlimited-ocr": ["vision", "decoder", "assets", "tokenizer"],
    # KitMineruReader / KitGlmOcrReader: the recognition bundle's two halves.
    "mineru2.5-pro": ["vision", "decoder"],
    "glm-ocr": ["vision", "decoder"],
    # AudioModelID (Audio/KitAudioModel.swift): thinker decoder + audio encoder.
    "qwen2.5-omni-3b-audio": ["gpu-pipelined/qwen2_5_omni_3b_thinker_int8lin_n750_s1",
                              "gpu-pipelined/qwen2_5_omni_3b_audio_encoder_fp16_k15"],
}


def downloaded_paths(entry: dict, key: str) -> list[str]:
    """Every repo path a first run of variant `key` downloads, as ModelStore addresses them."""
    if entry["id"] in INSTEAD:
        return INSTEAD[entry["id"]]
    also = ALSO.get(entry["id"], [])
    if isinstance(also, dict):
        also = also.get(key, [])
    return [entry["variants"][key]["path"], *also]


def files_under(path: str, files: dict[str, int]) -> dict[str, int]:
    """The files ModelStore fetches for `path`: the file itself, or everything below it."""
    path = path.strip("/")
    return {name: size for name, size in files.items()
            if not path or name == path or name.startswith(path + "/")}


def repo_files(repo: str, revision: str) -> dict[str, int]:
    """{path: bytes} for every file in the repo at `revision` (the listing
    `huggingface_hub.HfApi().repo_info(..., files_metadata=True)` makes)."""
    url = (f"https://huggingface.co/api/models/{repo}/revision/"
           f"{urllib.parse.quote(revision, safe='')}?blobs=true")
    for attempt in range(4):
        try:
            with urllib.request.urlopen(url, timeout=60) as response:
                info = json.load(response)
            return {s["rfilename"]: s.get("size") or 0 for s in info["siblings"]}
        except urllib.error.HTTPError as error:
            if error.code != 429 and error.code < 500:
                raise
            if attempt == 3:
                raise
        except (urllib.error.URLError, TimeoutError):
            if attempt == 3:
                raise
        time.sleep(2 ** attempt)
    raise AssertionError("unreachable")


def write_swift(sizes: dict[tuple[str, str], int]) -> int:
    """Set each (id, variant key) sizeMB in the built-in literal; returns how many changed."""
    text = SWIFT.read_text()
    starts = [(m.start(), m.group(1))
              for m in re.finditer(r'CatalogEntry\(\s*id:\s*"([^"]+)"', text)]
    pieces, cursor, changed, seen = [], 0, 0, set()
    for i, (start, entry_id) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(text)
        block = text[start:end]
        for key in [k for (eid, k) in sizes if eid == entry_id]:
            pattern = re.compile(r'("' + re.escape(key) + r'"\s*:\s*\.init\(\s*path:\s*"[^"]*"'
                                 r'\s*,\s*sizeMB:\s*)(\d+)')
            matches = pattern.findall(block)
            if len(matches) != 1:
                sys.exit(f"{SWIFT.name}: expected one {key} variant in '{entry_id}', "
                         f"found {len(matches)}")
            new = sizes[(entry_id, key)]
            if int(matches[0][1]) != new:
                block = pattern.sub(lambda m: m.group(1) + str(new), block)
                changed += 1
            seen.add((entry_id, key))
        pieces += [text[cursor:start], block]
        cursor = end
    missing = sorted(set(sizes) - seen)
    if missing:
        sys.exit(f"{SWIFT.name}: no built-in variant for {missing}")
    SWIFT.write_text("".join(pieces) + text[cursor:])
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help=f"exit 1 if a declared size is more than {TOLERANCE:.0%} off")
    mode.add_argument("--write", action="store_true",
                      help="set every sizeMB in catalog.json and the built-in literal")
    parser.add_argument("--only", help="one catalog id")
    args = parser.parse_args()

    catalog = json.loads(CATALOG.read_text())
    measured: dict[tuple[str, str], int] = {}
    drifted, broken, unreadable = [], [], []

    print(f"{'model':<34}{'variant':<14}{'declared':>9}{'measured':>10}{'bytes':>17}")
    for entry in catalog["models"]:
        if args.only and entry["id"] != args.only:
            continue
        try:
            files = repo_files(entry["repo"], entry["revision"])
        except Exception as error:  # noqa: BLE001 — reported, like pin-catalog.py --check
            unreadable.append(f"{entry['id']}: {error}")
            continue
        for key, variant in entry["variants"].items():
            fetched: dict[str, int] = {}
            for path in downloaded_paths(entry, key):
                under = files_under(path, files)
                if not under:
                    broken.append(f"{entry['id']} {key}: nothing at '{path}' "
                                  f"@ {entry['revision'][:12]}")
                fetched |= under
            total = sum(fetched.values())
            exact_mb = total / 1_000_000
            size_mb = round(exact_mb)
            declared = variant.get("sizeMB")
            off = declared is None or abs(declared - exact_mb) > TOLERANCE * exact_mb
            if off:
                drifted.append((entry["id"], key, declared, size_mb))
            measured[(entry["id"], key)] = size_mb
            print(f"{entry['id']:<34}{key:<14}{str(declared):>9}{size_mb:>10}"
                  f"{total:>17,}" + ("  <- off by more than 2%" if off else ""))

    for line in unreadable:
        print(f"WARNING: could not read {line}", file=sys.stderr)
    for line in broken:
        print(f"FAIL: {line}", file=sys.stderr)
    if broken:
        return 1

    if args.write:
        changed = 0
        for entry in catalog["models"]:
            for key, variant in entry["variants"].items():
                new = measured.get((entry["id"], key))
                if new is not None and variant.get("sizeMB") != new:
                    variant["sizeMB"] = new
                    changed += 1
        CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n")
        swift_changed = write_swift(measured)
        print(f"\nwrote {changed} sizes to {CATALOG.name}, {swift_changed} to {SWIFT.name}")
        return 0

    if drifted:
        print(f"\n{len(drifted)} declared sizes are more than {TOLERANCE:.0%} off what a first "
              "run downloads. Fix with:\n  python3 scripts/measure-catalog-sizes.py --write",
              file=sys.stderr)
        return 1 if args.check else 0
    print(f"\nOK: {len(measured)} variant sizes within {TOLERANCE:.0%} of the Hub"
          + (f" ({len(unreadable)} repos unreadable)" if unreadable else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
